"""empty message

Revision ID: df9c32390172
Revises: 81a2d95990ef
Create Date: 2024-05-01 17:45:14.150338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9c32390172'
down_revision = '81a2d95990ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('seeking_venue_description', new_column_name='seeking_description')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.alter_column('seeking_talent_description', new_column_name='seeking_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('seeking_description', new_column_name='seeking_talent_description')
        batch_op.drop_column('website')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('seeking_description', new_column_name='seeking_venue_description')

    # ### end Alembic commands ###
